Add tests for translated key order and some cases of duplicate keys.
codeigniter4/translations pull request #187
Opened 2020-12-13 13:37 UTC by sfadschm

This adds a test method to check whether the order of the translated keys is the same as in the main repo.
At the same time, this also protects against duplicate key definitions in translated file, but not all possible cases.

Example that will trigger an error:

    'key1' => 'val1',
    'key2' => 'val2',
    'key1' => 'val3',

Example that will not trigger an error:

    'key1' => 'val1',
    'key1' => 'val3',
    'key2' => 'val2',

Example output for current `it` locale:

    Failed asserting that the translated language keys in "it" locale have the same order as the original keys in the main repository. This can also be caused by duplicate key definitions. First mismatch per file:
    Migrations:
      - 26 => 'migSeeder'
      + 26 => 'on'  
    Validation:
     - 26 => 'matches'
     + 26 => 'string'
    Failed asserting that an array is empty.

I would think the other cases of duplicate keys are pretty obvious to see when editing a translation file and should not occur too often. If we wanted to check them too, we would need to `file_get_contents` the language files and compare the line on which each key is defined (or the total number of lines in the file). This would of course also require us to have consistent comments and blank lines in the files (which is not a bad thing in my opinion).

2020-12-13 14:03 UTC, paulbalandan requested changes

2020-12-13 14:03 UTC, paulbalandan commented on tests/Language/AbstractTranslationTestCase.php
> +				return "  - $key1 => '$val1' \n  + $key1 => '$val2'";
```suggestion
				return "  - $key1 => '$val1'\n  + $key1 => '$val2'";
```

2020-12-13 14:03 UTC, paulbalandan commented on tests/Language/AbstractTranslationTestCase.php
> +	 * @return sting
```suggestion
	 * @return string
```

2020-12-13 14:03 UTC, paulbalandan commented on tests/Language/AbstractTranslationTestCase.php
> +	 * @param array $array2
```suggestion
	 * @param array<string, string> $array1
	 * @param array<string, string> $array2
```

2020-12-13 14:31 UTC, sfadschm commented on tests/Language/AbstractTranslationTestCase.php
> +			'Failed asserting that the translated language keys in "%s" locale have the same order as the original keys in the main repository. This can also be caused by duplicate key definitions. First mism
Will make more precise. Do you mean merging into a single line message?

2020-12-13 14:50 UTC, sfadschm commented on tests/Language/AbstractTranslationTestCase.php
> +		array_walk($diffs, fn(&$item, $key) => $item = $key.":\n".$item);
Removed the need for `array_walk`.

2020-12-13 14:52 UTC, sfadschm commented on tests/Language/AbstractTranslationTestCase.php
> +		array_walk($diffs, fn(&$item, $key) => $item = $key.":\n".$item);
Refactored the message to 

    Failed asserting that the translated language keys in "it" locale are ordered correctly. "Migrations.php" index "26" is "on", should be "migSeeder". "Validation.php" index "26" is "string", should be "matches".
Failed asserting that an array is empty.

Is this more like expected?

2020-12-13 15:22 UTC, paulbalandan commented on tests/Language/AbstractTranslationTestCase.php
> +			'Failed asserting that the translated language keys in "%s" locale have the same order as the original keys in the main repository. This can also be caused by duplicate key definitions. First mism
I mean here is you used concat on all strings which is useless.

2020-12-13 15:23 UTC, paulbalandan commented on tests/Language/AbstractTranslationTestCase.php
> +		array_walk($diffs, fn(&$item, $key) => $item = $key.":\n".$item);
I would like the second sentence to be the earlier `git diff` format. That's visually better, I think

2020-12-13 15:58 UTC, sfadschm commented on tests/Language/AbstractTranslationTestCase.php
> +			'Failed asserting that the translated language keys in "%s" locale have the same order as the original keys in the main repository. This can also be caused by duplicate key definitions. First mism
Oh right, I thought we were going with `''` for strings, but `""` is required for newlines to be interpreted. Will change.

2020-12-13 17:11 UTC, paulbalandan approved these changes
I have some visual adjustments but I'll just do that myself in a later PR.

2020-12-13 17:11 UTC, merged

2020-12-14 12:30 UTC, MGatner commented
Very nice work, thank you team.