add missing translate (uploadErrUnknown)
codeigniter4/translations pull request #323
Opened 2022-08-24 07:38 UTC by msalehi-d

2022-08-24 08:56 UTC, kenjis commented
Thank you!

But it seems there are some missing translations.
Can you fix?

```
There were 2 failures:

1) Translations\Tests\FarsiTranslationTest::testAllConfiguredLanguageFilesAreTranslated with data set "fa" ('fa')
Failed asserting that language files "CLI.php", "Cast.php", "Cookie.php", "Encryption.php", "Fabricator.php", "Filters.php", "Publisher.php", "RESTful.php", "Security.php", "Test.php" in the main repository are translated in "fa" locale.
Failed asserting that an array is empty.

/home/runner/work/translations/translations/tests/Language/AbstractTranslationTestCase.php:108
phpvfscomposer:///home/runner/work/translations/translations/vendor/phpunit/phpunit/phpunit:97

2) Translations\Tests\FarsiTranslationTest::testAllConfiguredLanguageKeysAreIncluded with data set "fa" ('fa')
Failed asserting that the language keys "Core.enabledZlibOutputCompression", "Core.invalidPhpVersion", "Database.emptyPrimaryKey", "Database.fieldNotExists", "Database.forEmptyInputGiven", "Database.forFindColumnHaveMultipleColumns", "Database.methodNotAvailable", "Database.noDateFormat", "Database.noPrimaryKey", "Database.parseStringFail", "Database.tableNotFound", "Email.exitStatus", "Files.expectedDirectory", "Files.expectedFile", "Format.invalidFormatter", "Format.invalidMime", "HTTP.controllerNotFound", "HTTP.emptyController", "HTTP.invalidSameSiteSetting", "HTTP.methodNotFound", "Images.fileNotSupported", "Images.webpNotSupported", "Log.invalidMessageType", "Migrations.added", "Migrations.batch", "Migrations.batchNotFound", "Migrations.filename", "Migrations.generalFault", "Migrations.group", "Migrations.latest", "Migrations.migCreate", "Migrations.migHelpCurrent", "Migrations.migHelpLatest", "Migrations.migHelpRefresh", "Migrations.migHelpRollback", "Migrations.migHelpSeed", "Migrations.migHelpVersion", "Migrations.migInvalidVersion", "Migrations.migMissingSeeder", "Migrations.migNumberError", "Migrations.migSeeder", "Migrations.migrated", "Migrations.nameMigration", "Migrations.nameSeeder", "Migrations.namespace", "Migrations.noneFound", "Migrations.on", "Migrations.refreshConfirm", "Migrations.removed", "Migrations.rollBackConfirm", "Migrations.rollingBack", "Migrations.toVersion", "Migrations.toVersionPH", "Migrations.version", "Router.invalidControllerName", "Router.invalidDynamicController", "Session.invalidSameSiteSetting", "Time.invalidFormat", "Validation.alpha_numeric_punct", "Validation.equals", "Validation.hex", "Validation.is_not_unique", "Validation.not_equals", "Validation.not_in_list", "Validation.string", "View.invalidCellClass", "View.invalidDecoratorClass", "View.noCellClass", "View.tagSyntaxError" in the main repository are included for translation in "fa" locale.
Failed asserting that an array is empty.

/home/runner/work/translations/translations/tests/Language/AbstractTranslationTestCase.php:166
phpvfscomposer:///home/runner/work/translations/translations/vendor/phpunit/phpunit/phpunit:97
```

2022-08-25 08:24 UTC, msalehi-d commented
It may take a while, but I'll work on it.

2022-08-27 12:17 UTC, totoprayogo1916 reviewed
`Language/Cast.php` should be removed

2022-08-28 06:50 UTC, msalehi-d commented
> `Language/Cast.php` should be removed

Thanks. It still exists in the CI4 fresh installation.

2022-08-28 07:27 UTC, paulbalandan commented
> > `Language/Cast.php` should be removed
> 
> Thanks. It still exists in the CI4 fresh installation.

@totoprayogo1916 meant was to move `Language/Cast.php` to `Language/fa/Cast.php`

2022-08-28 07:29 UTC, paulbalandan requested changes

2022-08-28 07:29 UTC, paulbalandan commented on Language/fa/Cookie.php
> +',
```suggestion
    'invalidExpiresTime'    => 'نوع داده {0} برای ویژگی "Expires" معتبر نیست. نوع داده های معتبر: string, integer, DateTimeInterface object.',
```

2022-08-28 07:29 UTC, paulbalandan commented on Language/fa/Validation.php
> +
Remove trailing whitespace.
```suggestion
```

2022-08-28 07:29 UTC, paulbalandan commented on Language/fa/View.php
> +    'invalidDecoratorClass' => '{0} یک View Decorator معتبر نیست.',];
```suggestion
    'invalidDecoratorClass' => '{0} یک View Decorator معتبر نیست.',
];
```

2022-08-28 10:14 UTC, msalehi-d commented
Why all changes for most of the files are gone? Last update is 12 months ago

2022-08-28 10:55 UTC, paulbalandan commented
It seems the maintainer for this locale is not active. If you have time, you can replace as maintainer.

2022-08-28 11:12 UTC, msalehi-d commented
@paulbalandan Yes please. I'll upload files again after that

2022-08-29 10:05 UTC, paulbalandan commented on Language/fa/Migrations.php
>      'missingTable' => 'جدول مایگریشن تنظیم نشده است.',
```suggestion
    'missingTable'  => 'جدول مایگریشن تنظیم نشده است.',
```

2022-08-29 10:05 UTC, paulbalandan commented on Language/fa/Router.php
> +
```suggestion
    'invalidParameter'         => 'یک پارامتر با مقدار مورد انتظار تطابق ندارد.',
    'missingDefaultRoute'      => 'امکان تشخیص محتوایی برای نمایش وجود ندارد. مسیر پیش فرض در فایل روتینگ مشخص نشده است.',
    'invalidDynamicController' => 'کنترلر داینامیک به دلایل امنیتی مجاز نیست.  Route handler: {0}',
    'invalidControllerName'    => 'برای جدا کننده‌ی فضای نام از بک اسلش (\) استفاده کنید، نه اسلش (/). Route handler: {0}',
```

2022-08-29 10:24 UTC, paulbalandan commented on Language/fa/HTTP.php
>  <?php
```suggestion
<?php
```

2022-08-29 10:24 UTC, paulbalandan commented on Language/fa/Validation.php
> +    'valid_cc_num' => 'فیلد {field} به نظر یک شماره کارت اعتباری معتبر نیست.',
```suggestion
    'valid_cc_num' => 'فیلد {field} به نظر یک شماره کارت اعتباری معتبر نیست.',

```

2022-08-29 10:36 UTC, paulbalandan commented on Language/fa/Cast.php
> +<?php
```suggestion
<?php
```

2022-08-29 10:39 UTC, paulbalandan approved these changes

2022-08-29 10:39 UTC, merged

2022-08-29 10:39 UTC, paulbalandan commented
Thank you, @msalehi-d